//! Command-line argument parsing.
//!
//! Thin wrapper over `clap`'s derive API. Keeps CLI-shape concerns out of
//! `main.rs` so future flags (themes, alternate modes, etc.) have a
//! natural home.

use std::path::PathBuf;

use clap::Parser;

/// TypoCode — terminal typing game that uses source code as practice text.
///
/// Pass a path to the file you want to type through. `--help` / `-h` and
/// `--version` / `-V` are generated by clap.
#[derive(Debug, Parser)]
#[command(name = "typocode", version, about, long_about = None)]
pub struct Cli {
    /// Path to the source file to load as the typing challenge.
    pub path: PathBuf,
}

impl Cli {
    /// Parses the process arguments into a [`Cli`]. Exits the process via
    /// clap when the user passes `-h`, `-V`, or provides invalid args.
    pub fn parse_args() -> Self {
        Self::parse()
    }
}
